
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ssq-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    
  frontend:
    build: ./frontend
    container_name: ssq-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend